### ISSUE TITLE
Upload error.

### ISSUE THREAD

**Issue by zholbrook** [samwang0723/URLSessionUpload#1]
The xcode prodject seems fine but I get and error during upload of the file.Also i have been searching for a project like this forever, thanks for any help.

Exception happened during processing of request from ('192.168.1.9', 51231)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "C:\Python27\HTTPServerwithUpload.py", line 14, in do_POST
    ctype, pdict = cgi.parse_header(self.headers.getheader('content-tytpe'))
  File "C:\Python27\lib\cgi.py", line 309, in parse_header
    parts = _parseparam(';' + line)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by zholbrook** [comment]
@samwang0723
